title: Portfólio Rodrigo Pereira
description: Projetos e Cases
show_downloads: false
google_analytics: G-JRLBM576BT
theme: jekyll-theme-slate

# Mantém o footer, mas remove do header
github:
  is_project_page: false
